export enum ActionTypes {
  GET_PENDING = 'GET_PENDING',
  COMPLETE_REQUEST = 'COMPLETE_REQUEST',
  HAS_WALLET = 'HAS_WALLET',
  GET_WALLET = 'GET_WALLET',
  GET_MNEMONIC = 'GET_MNEMONIC',
  GET_LAST_ACCOUNT_USED = 'GET_LAST_ACCOUNT_USED',
  SET_LAST_ACCOUNT_USED = 'SET_LAST_ACCOUNT_USED',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
  UNLOCK_WALLET = 'UNLOCK_WALLET',
}
export enum GlobalActionTypes {
  GET_PENDING = 'extension/GET_PENDING',
  COMPLETE_REQUEST = 'extension/COMPLETE_REQUEST',
  HAS_WALLET = 'extension/HAS_WALLET',
  GET_WALLET = 'extension/GET_WALLET',
  GET_MNEMONIC = 'extension/GET_MNEMONIC',
  GET_LAST_ACCOUNT_USED = 'extension/GET_LAST_ACCOUNT_USED',
  SET_LAST_ACCOUNT_USED = 'extension/SET_LAST_ACCOUNT_USED',
  CREATE_ACCOUNT = 'extension/CREATE_ACCOUNT',
  UPDATE_ACCOUNT = 'extension/UPDATE_ACCOUNT',
  UNLOCK_WALLET = 'extension/UNLOCK_WALLET',
}
