export enum ActionTypes {
  GET_PENDING = 'GET_PENDING',
  COMPLETE_REQUEST = 'COMPLETE_REQUEST',
  GET_WALLET = 'GET_WALLET',
  CREATE_WALLET = 'CREATE_WALLET'
}
export enum GlobalActionTypes {
  GET_PENDING = 'extension/GET_PENDING',
  COMPLETE_REQUEST = 'extension/COMPLETE_REQUEST',
  GET_WALLET = 'extension/GET_WALLET',
  CREATE_WALLET = 'extension/CREATE_WALLET',
}
