name: Extension Build
on: 
  pull_request:
    paths:
      - "packages/emeris-extension/**"
defaults:
  run:
    working-directory: ./packages/emeris-extension/
jobs:
  Extension-Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}

      - run: git submodule init && git submodule update
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: |
            ./packages/emeris-extension/yarn.lock
            ./packages/signer/package-lock.json
            ./packages/mapper/package-lock.json
            ./packages/types/package-lock.json
            ./packages/emeris-extension/demeris/package-lock.json

      - name: build artifacts
        run: |
          cd ../..
          npx lerna bootstrap
          NODE_OPTIONS="--max_old_space_size=8192" NODE_ENV="production" npx lerna run build
        env:
          # Put in secrets
          VUE_APP_EMERIS_PROD_ENDPOINT: https://api.emeris.com/v1
          VUE_APP_EMERIS_PROD_LIQUIDITY_ENDPOINT: https://api.emeris.com/v1/liquidity

      - run: echo "PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV
      - uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ./packages/emeris-extension/dist
          filename: preview-${{ env.PR_NUMBER }}.zip
      - uses: actions/upload-artifact@v3
        with:
          name: preview-${{ env.PR_NUMBER }}.zip
          path: ./packages/emeris-extension/dist/preview-${{ env.PR_NUMBER }}.zip
          retention-days: 10
