name: Extension Build
on: 
  pull_request:
    paths:
      - "packages/browser-extension/**"
defaults:
  run:
    working-directory: ./packages/browser-extension/
jobs:
  Extension-Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}
      - run: git submodule init && git submodule update
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: |
            ./packages/browser-extension/yarn.lock
            ./packages/signer/yarn.lock
            ./packages/browser-extension/demeris/package-lock.json

      - name: Build and link local packages
        run: |
          cd ../signer
          yarn install --frozen-lockfile
          cd ../mapper
          yarn install --frozen-lockfile
          npm run build
          yarn link
          cd ../browser-extension
          yarn link @emeris/signer

      - name: Install extension packages
        run: yarn install --frozen-lockfile
      - name: Install demeris packages
        run: |
          cd ./demeris
          yarn install --frozen-lockfile

      - name: build artifacts
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4048

      - uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ./packages/browser-extension/dist
          filename: release.zip
      - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ github.token }}
          artifacts-branch: artifacts
          artifacts: |
            ./packages/browser-extension/dist/release.zip