name: Extension Build
on: [push]
defaults:
  run:
    working-directory: ./packages/browser-extension/
jobs:
  Extension-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: git submodule init && git submodule update
      - name: build artifacts
        run: npm run build
      - uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: ./dist
          filename: release.zip
      - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ github.token }}
          artifacts-branch: artifacts
          artifacts: |
            release.zip