name: Extension Build
on: 
  pull_request:
    paths:
      - "packages/browser-extension/**"
defaults:
  run:
    working-directory: ./packages/browser-extension/
jobs:
  Extension-Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}
      - run: git submodule init && git submodule update
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache-dependency-path: |
            ./packages/browser-extension/package-lock.json
            ./packages/signer/package-lock.json
            ./packages/mapper/package-lock.json
            ./packages/types/package-lock.json
            ./packages/browser-extension/demeris/package-lock.json

      - run: sudo apt-get install libpng16-dev
      - name: build artifacts
        run: |
          cd ../..
          npx lerna bootstrap
          NODE_OPTIONS=--max_old_space_size=4096 npx lerna run build
        env:
          # Put in secrets
          VUE_APP_EMERIS_PROD_ENDPOINT: https://api.emeris.com/v1
          VUE_APP_EMERIS_PROD_LIQUIDITY_ENDPOINT: https://api.emeris.com/v1/liquidity

      - uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ./packages/browser-extension/dist
          filename: release.zip
      - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ github.token }}
          artifacts-branch: artifacts
          artifacts: |
            ./packages/browser-extension/dist/release.zip