name: PR release & deploy

# Controls when the action will run. 
on:
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          
      - name: Publish
        run: npx lerna publish --force-publish --canary --preid pr-{{ github.event.number }}-$(git rev-parse HEAD) --dist-tag pr-{{ github.event.number }} --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH}}

      
